server:
  port: 9005

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: solus19910808
    url: jdbc:mysql://localhost:9001/simple_ledger?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml